name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.6.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.6.3.stable ~/.local/share/godot/export_templates/4.6.3.stable

      - name: Create debug keystore
        run: |
          keytool -keyalg RSA -genkeypair -alias android \
            -keypass android -keystore debug.keystore \
            -storepass android -dname "CN=,OU=,O=,L=,S=,C=" \
            -validity 9999
          cp debug.keystore /root/debug.keystore

      - name: Export APK
        run: |
          mkdir -v -p build/android
          godot --headless --verbose --export-debug "Android" build/android/math-quiz.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: math-quiz-android
          path: build/android/math-quiz.apk
